services:
  scam_detection:
    build: .
    volumes:
      - .:/app
      - ./.uv-cache:/app/.uv-cache
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    ports:
      - "5000:5000"
    volumes:
      - ./artifacts/mlflow:/mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    command: mlflow server --host 0.0.0.0 --port 5000
